//import {Arial} from 'next/font/google';
import "./globals.css";
//css modules below
import stylesG from './stylesG.module.css'

/*const arial = Arial({
subsets: ["latin"],
});*/

export const metadata = {
  title: "NEXO",
  description: "Generated by Diego y Victor",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={stylesG.html}>
      <body className={stylesG.body__container}>
        <header className={stylesG.header}>
          <ul className={stylesG.header__element}><input type="button" value="" />Logo</ul>
          <ul className={stylesG.header__element}><input type="button" value="" />Notificacion</ul>
        </header>
        <main className={stylesG.main}>
          <aside className={stylesG.lateralBar}>
            <ul className={stylesG.lateralBar__element}>
              <a href="/" rel="noopener noreferrer">Inicio</a>
            </ul>
            <ul className={stylesG.lateralBar__element}>
              <a href="/team" rel="noopener noreferrer">Mi equipo</a>
            </ul>
            <ul className={stylesG.lateralBar__element}>
              <a href="/dashboards" rel="noopener noreferrer">Reportes</a>
            </ul>
            <ul className={stylesG.lateralBar__element}>
              <a href="/cases" rel="noopener noreferrer">Casos</a>
            </ul>
          </aside>
          {children}
        </main>
      </body>

    </html>
  );
}